"""Machine-readable API description for the JIRA tool.

Provides the full command surface so LLMs can discover capabilities
without parsing --help text.
"""

from llm_tool_common import Argument, Command, ToolDescription


def get_tool_description() -> ToolDescription:
    """Return the complete JIRA tool API description."""
    return ToolDescription(
        name="jira",
        version="0.2.0",
        description="JIRA CLI tool for LLM agents. Provides issue tracking operations with structured JSON output.",
        env_vars=[
            {"name": "JIRA_SERVER", "description": "JIRA server URL", "required": "true"},
            {"name": "JIRA_TOKEN", "description": "JIRA API token", "required": "true"},
        ],
        commands=[
            Command(
                name="get",
                description="Get issue details by key or URL, optionally with comments",
                usage="jira get <KEY> [--comments]",
                arguments=[
                    Argument(name="key", description="Issue key (e.g., PROJ-123) or JIRA URL", required=True),
                    Argument(name="--fields", description="Comma-separated list of fields to return"),
                    Argument(name="--output", description="Output only this field as plain text (no JSON envelope)"),
                    Argument(name="--comments", description="Include first 5 comments inline", type="boolean", default=False),
                ],
                examples=[
                    "jira get PROJ-123",
                    "jira get PROJ-123 --comments",
                    "jira get https://jira.example.com/browse/PROJ-123",
                    "jira get PROJ-123 --output status",
                ],
                output_fields=["key", "id", "summary", "description", "status", "priority", "issue_type", "project", "assignee", "reporter", "resolution", "created", "updated", "labels", "comments", "total_comments"],
                next_actions=["comments", "transitions", "attachments", "links"],
            ),
            Command(
                name="comments",
                description="Get comments for an issue with pagination",
                usage="jira comments <KEY> [--limit N] [--offset N]",
                arguments=[
                    Argument(name="key", description="Issue key or JIRA URL", required=True),
                    Argument(name="--limit", description="Maximum comments to return", type="integer", default=5),
                    Argument(name="--offset", description="Skip first N comments", type="integer", default=0),
                    Argument(name="--all", description="Fetch all comments", type="boolean", default=False),
                    Argument(name="--summary-only", description="Only return comment metadata, not full content", type="boolean", default=False),
                    Argument(name="--oldest-first", description="Sort oldest first (default is newest first)", type="boolean", default=False),
                ],
                examples=[
                    "jira comments PROJ-123",
                    "jira comments PROJ-123 --limit 10 --oldest-first",
                    "jira comments PROJ-123 --summary-only",
                ],
                output_fields=["issue_key", "total_comments", "comments[].id", "comments[].body", "comments[].author", "comments[].created", "pagination"],
                next_actions=["comment (to add)", "get"],
            ),
            Command(
                name="search",
                description="Search issues using JQL",
                usage='jira search "<JQL>" [--limit N]',
                arguments=[
                    Argument(name="jql", description="JIRA Query Language query string", required=True),
                    Argument(name="--limit", description="Maximum results", type="integer", default=20),
                    Argument(name="--offset", description="Skip first N results", type="integer", default=0),
                    Argument(name="--fields", description="Comma-separated fields to return"),
                    Argument(name="--output", description="Output only this field from each issue (one per line)"),
                ],
                examples=[
                    'jira search "project = PROJ AND status = Open"',
                    'jira search "assignee = currentUser()" --limit 5',
                    'jira search "project = PROJ" --output key',
                ],
                output_fields=["jql", "issues[]", "pagination"],
                next_actions=["get (with a specific key from results)"],
            ),
            Command(
                name="comment",
                description="Add a comment to an issue",
                usage='jira comment <KEY> "<BODY>"',
                arguments=[
                    Argument(name="key", description="Issue key or JIRA URL", required=True),
                    Argument(name="body", description="Comment text", required=True),
                ],
                examples=['jira comment PROJ-123 "Fixed in commit abc123"'],
                output_fields=["issue_key", "comment.id", "comment.body", "comment.author", "comment.created"],
                next_actions=["get", "transition"],
            ),
            Command(
                name="edit-comment",
                description="Edit an existing comment on an issue",
                usage='jira edit-comment <KEY> <COMMENT_ID> "<BODY>"',
                arguments=[
                    Argument(name="key", description="Issue key or JIRA URL", required=True),
                    Argument(name="comment_id", description="Numeric comment ID to edit", required=True),
                    Argument(name="body", description="New comment text", required=True),
                ],
                examples=['jira edit-comment PROJ-123 12345 "Updated comment text"'],
                output_fields=["issue_key", "comment.id", "comment.body", "comment.author", "comment.updated"],
                next_actions=["get", "comments"],
            ),
            Command(
                name="link",
                description="Create a link between two issues",
                usage="jira link <KEY> <TARGET_KEY> [--type TYPE]",
                arguments=[
                    Argument(name="key", description="Source issue key or JIRA URL", required=True),
                    Argument(name="target_key", description="Target issue key", required=True),
                    Argument(name="--type", description="Link type name (Related, Blocks, Duplicate, etc.)", default="Related"),
                ],
                examples=[
                    "jira link PROJ-123 PROJ-456",
                    "jira link PROJ-123 PROJ-456 --type Blocks",
                ],
                output_fields=["source_key", "target_key", "link_type"],
                next_actions=["links", "get"],
            ),
            Command(
                name="delete-comment",
                description="Delete a comment from an issue",
                usage="jira delete-comment <KEY> <COMMENT_ID>",
                arguments=[
                    Argument(name="key", description="Issue key or JIRA URL", required=True),
                    Argument(name="comment_id", description="Numeric comment ID to delete", required=True),
                ],
                examples=["jira delete-comment PROJ-123 12345"],
                output_fields=["issue_key", "comment_id", "deleted"],
                next_actions=["comments"],
            ),
            Command(
                name="unlink",
                description="Remove a link between two issues",
                usage="jira unlink <LINK_ID>",
                arguments=[
                    Argument(name="link_id", description="Numeric link ID (from 'jira links' output)", required=True),
                ],
                examples=["jira unlink 54321"],
                output_fields=["link_id", "deleted"],
                next_actions=["links"],
            ),
            Command(
                name="link-types",
                description="List available issue link types",
                usage="jira link-types",
                arguments=[],
                examples=["jira link-types"],
                output_fields=["total", "link_types[].id", "link_types[].name", "link_types[].inward", "link_types[].outward"],
                next_actions=["link"],
            ),
            Command(
                name="add-label",
                description="Add one or more labels to an issue",
                usage="jira add-label <KEY> <LABEL> [<LABEL> ...]",
                arguments=[
                    Argument(name="key", description="Issue key or JIRA URL", required=True),
                    Argument(name="labels", description="Label names to add", required=True),
                ],
                examples=["jira add-label PROJ-123 urgent", "jira add-label PROJ-123 urgent blocker"],
                output_fields=["issue_key", "labels_added"],
                next_actions=["get"],
            ),
            Command(
                name="remove-label",
                description="Remove one or more labels from an issue",
                usage="jira remove-label <KEY> <LABEL> [<LABEL> ...]",
                arguments=[
                    Argument(name="key", description="Issue key or JIRA URL", required=True),
                    Argument(name="labels", description="Label names to remove", required=True),
                ],
                examples=["jira remove-label PROJ-123 urgent"],
                output_fields=["issue_key", "labels_removed"],
                next_actions=["get"],
            ),
            Command(
                name="components",
                description="List components for a project",
                usage="jira components <PROJECT_KEY>",
                arguments=[
                    Argument(name="project_key", description="Project key (e.g., LU, EX)", required=True),
                ],
                examples=["jira components LU"],
                output_fields=["project_key", "total", "components[].id", "components[].name", "components[].description"],
                next_actions=["set-component"],
            ),
            Command(
                name="set-component",
                description="Set components on an issue (replaces existing)",
                usage="jira set-component <KEY> <COMPONENT> [<COMPONENT> ...]",
                arguments=[
                    Argument(name="key", description="Issue key or JIRA URL", required=True),
                    Argument(name="components", description="Component names to set", required=True),
                ],
                examples=["jira set-component LU-19900 lov"],
                output_fields=["issue_key", "components"],
                next_actions=["get"],
            ),
            Command(
                name="versions",
                description="List versions for a project",
                usage="jira versions <PROJECT_KEY>",
                arguments=[
                    Argument(name="project_key", description="Project key (e.g., LU, EX)", required=True),
                ],
                examples=["jira versions LU"],
                output_fields=["project_key", "total", "versions[].id", "versions[].name", "versions[].released", "versions[].release_date"],
                next_actions=["set-fix-version"],
            ),
            Command(
                name="set-fix-version",
                description="Set fix versions on an issue (replaces existing)",
                usage="jira set-fix-version <KEY> <VERSION> [<VERSION> ...]",
                arguments=[
                    Argument(name="key", description="Issue key or JIRA URL", required=True),
                    Argument(name="versions", description="Version names to set", required=True),
                ],
                examples=["jira set-fix-version LU-19900 2.16.0"],
                output_fields=["issue_key", "fix_versions"],
                next_actions=["get"],
            ),
            Command(
                name="create-subtask",
                description="Create a subtask under a parent issue",
                usage="jira create-subtask <PARENT_KEY> --summary <TEXT>",
                arguments=[
                    Argument(name="parent_key", description="Parent issue key", required=True),
                    Argument(name="--summary", description="Subtask summary", required=True),
                    Argument(name="--description", description="Subtask description"),
                ],
                examples=["jira create-subtask PROJ-123 --summary \"Implement widget\""],
                output_fields=["key", "id", "parent_key"],
                next_actions=["get", "subtasks"],
            ),
            Command(
                name="subtasks",
                description="List subtasks of an issue",
                usage="jira subtasks <KEY>",
                arguments=[
                    Argument(name="key", description="Issue key or JIRA URL", required=True),
                ],
                examples=["jira subtasks PROJ-123"],
                output_fields=["issue_key", "total", "subtasks[].key", "subtasks[].summary", "subtasks[].status"],
                next_actions=["get", "create-subtask"],
            ),
            Command(
                name="transitions",
                description="List available status transitions for an issue",
                usage="jira transitions <KEY>",
                arguments=[
                    Argument(name="key", description="Issue key or JIRA URL", required=True),
                ],
                examples=["jira transitions PROJ-123"],
                output_fields=["issue_key", "transitions[].id", "transitions[].name", "transitions[].to_status"],
                next_actions=["transition (with a transition ID from results)"],
            ),
            Command(
                name="transition",
                description="Transition an issue to a new status",
                usage="jira transition <KEY> <TRANSITION_ID>",
                arguments=[
                    Argument(name="key", description="Issue key or JIRA URL", required=True),
                    Argument(name="transition_id", description="Transition ID (from 'transitions' command)", required=True),
                    Argument(name="--comment", description="Add a comment with the transition"),
                ],
                examples=[
                    "jira transition PROJ-123 31",
                    'jira transition PROJ-123 31 --comment "Starting work"',
                ],
                output_fields=["issue_key", "transition_id", "status_before", "status_after", "comment_added"],
                next_actions=["get"],
            ),
            Command(
                name="create",
                description="Create a new issue",
                usage="jira create --project <KEY> --type <TYPE> --summary <TEXT>",
                arguments=[
                    Argument(name="--project", description="Project key (e.g., PROJ)", required=True),
                    Argument(name="--type", description="Issue type (e.g., Bug, Task)", required=True),
                    Argument(name="--summary", description="Issue summary", required=True),
                    Argument(name="--description", description="Issue description"),
                ],
                examples=[
                    'jira create --project PROJ --type Bug --summary "Login fails"',
                ],
                output_fields=["key", "id", "self"],
                next_actions=["get", "comment", "transition"],
            ),
            Command(
                name="update",
                description="Update fields on an existing issue",
                usage="jira update <KEY> [--summary TEXT] [--assignee USER] ...",
                arguments=[
                    Argument(name="key", description="Issue key or JIRA URL", required=True),
                    Argument(name="--summary", description="New summary"),
                    Argument(name="--description", description="New description"),
                    Argument(name="--assignee", description="New assignee (empty string to unassign)"),
                    Argument(name="--priority", description="New priority name"),
                    Argument(name="--labels", description="Comma-separated labels (replaces existing)"),
                ],
                examples=["jira update PROJ-123 --assignee jdoe --priority High"],
                output_fields=["issue_key", "updated_fields"],
                next_actions=["get"],
            ),
            Command(
                name="attachments",
                description="List attachments on an issue",
                usage="jira attachments <KEY>",
                arguments=[
                    Argument(name="key", description="Issue key or JIRA URL", required=True),
                ],
                examples=["jira attachments PROJ-123"],
                output_fields=["issue_key", "total", "attachments[].id", "attachments[].filename", "attachments[].size", "attachments[].mime_type"],
                next_actions=["attachment content (with an attachment ID from results)"],
            ),
            Command(
                name="links",
                description="List issue links (relationships to other issues)",
                usage="jira links <KEY>",
                arguments=[
                    Argument(name="key", description="Issue key or JIRA URL", required=True),
                ],
                examples=["jira links PROJ-123"],
                output_fields=["issue_key", "total", "links[].id", "links[].direction", "links[].relationship", "links[].issue_key", "links[].issue_summary"],
                next_actions=["get (with a linked issue key)", "unlink (with a link ID)"],
            ),
            Command(
                name="attachment content",
                description="Download attachment content (text files only by default)",
                usage="jira attachment content <ID> [--max-size BYTES]",
                arguments=[
                    Argument(name="attachment_id", description="Numeric attachment ID", required=True),
                    Argument(name="--max-size", description="Maximum size in bytes", type="integer", default=102400),
                    Argument(name="--encoding", description="Text encoding", default="utf-8"),
                    Argument(name="--raw", description="Output raw content (no JSON envelope)", type="boolean", default=False),
                ],
                examples=[
                    "jira attachment content 12345",
                    "jira attachment content 12345 --max-size 1048576",
                ],
                output_fields=["attachment", "size_bytes", "is_text", "content"],
            ),
            Command(
                name="attachment upload",
                description="Upload a file as an attachment to an issue",
                usage="jira attachment upload <KEY> <FILE_PATH>",
                arguments=[
                    Argument(name="key", description="Issue key or JIRA URL", required=True),
                    Argument(name="file_path", description="Path to file to upload", required=True),
                    Argument(name="--filename", description="Override filename"),
                ],
                examples=["jira attachment upload PROJ-123 /tmp/screenshot.png"],
                output_fields=["issue_key", "uploaded", "attachments"],
            ),
            Command(
                name="config test",
                description="Test connectivity to JIRA server",
                usage="jira config test",
                arguments=[],
                examples=["jira config test"],
                output_fields=["connected", "server_title", "version", "base_url"],
            ),
            Command(
                name="config show",
                description="Show current configuration (token redacted)",
                usage="jira config show",
                arguments=[],
                examples=["jira config show"],
                output_fields=["server", "token", "config_path"],
            ),
            Command(
                name="describe",
                description="Show this machine-readable API description",
                usage="jira describe",
                arguments=[
                    Argument(name="--command", description="Show description for a specific command only"),
                ],
                examples=["jira describe", "jira describe --command get"],
            ),
        ],
    )
